CREATE SEQUENCE CHANNEL_ID_SEQUENCE;

CREATE TABLE CHANNEL (
    ID          INTEGER NOT NULL DEFAULT NEXTVAL('CHANNEL_ID_SEQUENCE'),
    TITLE       VARCHAR,
    LINK        VARCHAR,
    DESCRIPTION TEXT
);

